#!/bin/sh

fetch() {
  case $# in
    1) curl --location --remote-name "$1" ;;
    2) curl --location "$1" --output "$2" ;;
  esac
}

mkdir -p packages
cd packages

fetch https://github.com/alexherbo2/node.js/raw/master/src/node.js
fetch https://suckless.org/logo.svg suckless.svg
fetch https://i.imgur.com/aSw7snN.png suckless.png
